import type { Story } from "./types";

export const MOCK_STORIES: Story[] = [
  {
    id: "a1b2c3d4-e5f6-7890-abcd-111111111111",
    mode: "news",
    template_key: "test-news-3",
    category: "News",
    input_language: "hi",
    slide_count: 4,
    image_source: null,
    voice_engine: "elevenlabs_pro",
    title: "ट्रम्प बोले: ईरान से तेल लेना पसंद, खार्ग द्वीप कब्जा की संभावना",
    slug: "trump-said-prefer-taking-oil-from-iran-possibility-of-seizing-kharg-island",
    timestamp_id: "300326094600956",
    description:
      "ट्रम्प ने ईरान से तेल लेने की इच्छा जताई, खार्ग द्वीप कब्जा की संभावना पर चर्चा, फारस की खाड़ी में अमेरिकी सेना की तैनाती तेज",
    keywords: [
      "डोनाल्ड ट्रंप",
      "ईरान तेल",
      "खार्ग द्वीप",
      "फारस की खाड़ी",
      "अमेरिकी सेना",
      "मध्य पूर्व तनाव",
    ],
    created_at: "2026-06-15T06:30:00Z",
    slides: [
      { placeholder_id: "cover", text: "ट्रम्प बोले: ईरान से तेल लेना पसंद, खार्ग द्वीप कब्जा की संभावना" },
      {
        placeholder_id: "section_1",
        text: "अमेरिकी राष्ट्रपति डोनाल्ड ट्रंप ने संकेत दिया कि ईरान के मुख्य तेल निर्यात केंद्र खार्ग द्वीप पर कब्जा संभव है। उन्होंने दावा किया कि इस द्वीप पर ईरान की रक्षा क्षमता नहीं है।",
      },
      {
        placeholder_id: "section_2",
        text: "संयुक्त राज्य ने फारस की खाड़ी क्षेत्र में हजारों सैनिकों और मरीन को तैनात किया है। इसी बीच, ट्रंप ने दावा किया कि पाकिस्तानी झंडे वाले तेल टैंकरों को स्ट्रेट ऑफ हॉरमुज़ से सुरक्षित गुजरने की अनुमति दी गई।",
      },
      { placeholder_id: "cta", text: "FOR MORE SUCH CONTENT : STAY CONNECTED WITH SUVICHAAR" },
    ],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-222222222222",
    mode: "news",
    template_key: "test-news-1",
    category: "Technology",
    input_language: "en",
    slide_count: 5,
    image_source: "ai",
    voice_engine: "azure_basic",
    title: "India's UPI Crosses 20 Billion Monthly Transactions — A Global First",
    slug: "india-upi-crosses-20-billion-monthly-transactions-global-first",
    timestamp_id: "150626081522340",
    description:
      "India's UPI digital payments platform sets a historic milestone, processing over 20 billion transactions in a single month.",
    keywords: ["UPI", "Digital Payments", "India", "Fintech", "RBI", "Technology"],
    created_at: "2026-06-15T08:15:00Z",
    slides: [
      { placeholder_id: "cover", text: "India's UPI Crosses 20 Billion Monthly Transactions — A Global First" },
      {
        placeholder_id: "section_1",
        text: "India's Unified Payments Interface (UPI) has crossed the historic milestone of 20 billion transactions in a single month, making it the largest real-time digital payment system in the world.",
      },
      {
        placeholder_id: "section_2",
        text: "The growth has been driven by Tier 2 and Tier 3 cities adopting digital payments rapidly. UPI now processes more transactions than all major card networks combined in India.",
      },
      {
        placeholder_id: "section_3",
        text: "RBI Governor highlighted that UPI's success is a model for other developing nations looking to build inclusive financial infrastructure.",
      },
      { placeholder_id: "cta", text: "FOR MORE SUCH CONTENT : STAY CONNECTED WITH SUVICHAAR" },
    ],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-333333333333",
    mode: "curious",
    template_key: "curious-template-1",
    category: "Science",
    input_language: "en",
    slide_count: 7,
    image_source: "ai",
    voice_engine: "azure_basic",
    title: "How Does Photosynthesis Actually Work?",
    slug: "how-does-photosynthesis-actually-work",
    timestamp_id: "140626143022781",
    description:
      "A visual explainer on how plants convert sunlight into energy — the most important chemical reaction on Earth.",
    keywords: ["Photosynthesis", "Science", "Biology", "Plants", "Education"],
    created_at: "2026-06-14T14:30:00Z",
    slides: [
      { placeholder_id: "cover", text: "How Does Photosynthesis Actually Work?" },
      {
        placeholder_id: "section_1",
        text: "Photosynthesis is the process by which green plants use sunlight, water, and carbon dioxide to create food (glucose) and release oxygen. It happens primarily in the leaves.",
      },
      {
        placeholder_id: "section_2",
        text: "Chlorophyll, the green pigment in leaves, captures light energy from the sun. This energy splits water molecules into hydrogen and oxygen in the 'light reactions'.",
      },
      {
        placeholder_id: "section_3",
        text: "In the Calvin Cycle (dark reactions), the hydrogen combines with CO₂ from the air to produce glucose — the plant's food source.",
      },
      {
        placeholder_id: "section_4",
        text: "A single large tree can produce enough oxygen for 4 people to breathe for an entire year through photosynthesis.",
      },
      {
        placeholder_id: "section_5",
        text: "Without photosynthesis, there would be no food chains, no breathable atmosphere, and essentially no life as we know it on Earth.",
      },
      { placeholder_id: "cta", text: "FOR MORE SUCH CONTENT : STAY CONNECTED WITH SUVICHAAR" },
    ],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-444444444444",
    mode: "news",
    template_key: "test-news-2",
    category: "Sports",
    input_language: "hi",
    slide_count: 4,
    image_source: "pexels",
    voice_engine: "elevenlabs_pro",
    title: "IPL 2026 Final: KKR ने RCB को हराकर तीसरी बार जीता खिताब",
    slug: "ipl-2026-final-kkr-beat-rcb-third-title",
    timestamp_id: "150626092130445",
    description: "कोलकाता नाइट राइडर्स ने आईपीएल 2026 फाइनल में रॉयल चैलेंजर्स बेंगलुरु को 8 विकेट से हराया",
    keywords: ["IPL 2026", "KKR", "RCB", "Cricket", "Final", "T20"],
    created_at: "2026-06-15T09:21:00Z",
    slides: [
      { placeholder_id: "cover", text: "IPL 2026 Final: KKR ने RCB को हराकर तीसरी बार जीता खिताब" },
      {
        placeholder_id: "section_1",
        text: "कोलकाता नाइट राइडर्स ने आईपीएल 2026 के फाइनल में रॉयल चैलेंजर्स बेंगलुरु को 8 विकेट से हराकर अपना तीसरा आईपीएल खिताब जीत लिया।",
      },
      {
        placeholder_id: "section_2",
        text: "KKR के कप्तान ने बेहतरीन अर्धशतक लगाते हुए टीम को जीत तक पहुँचाया। RCB ने पहले बल्लेबाजी करते हुए 165 रन का लक्ष्य रखा था।",
      },
      { placeholder_id: "cta", text: "FOR MORE SUCH CONTENT : STAY CONNECTED WITH SUVICHAAR" },
    ],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-555555555555",
    mode: "curious",
    template_key: "template-v19",
    category: "History",
    input_language: "en",
    slide_count: 8,
    image_source: "pexels",
    voice_engine: "elevenlabs_pro",
    title: "The Rise and Fall of the Maurya Empire",
    slug: "rise-and-fall-of-the-maurya-empire",
    timestamp_id: "140626184500328",
    description:
      "From Chandragupta to Ashoka — the story of India's first great empire that unified the subcontinent.",
    keywords: ["Maurya Empire", "Chandragupta", "Ashoka", "History", "India", "Ancient"],
    created_at: "2026-06-14T18:45:00Z",
    slides: [
      { placeholder_id: "cover", text: "The Rise and Fall of the Maurya Empire" },
      {
        placeholder_id: "section_1",
        text: "Founded by Chandragupta Maurya in 321 BCE with the guidance of Chanakya, the Maurya Empire was the first to unify most of the Indian subcontinent.",
      },
      {
        placeholder_id: "section_2",
        text: "Chandragupta defeated the Nanda dynasty and later pushed back the forces of Seleucus, establishing control from Afghanistan to Bengal.",
      },
      {
        placeholder_id: "section_3",
        text: "His grandson, Emperor Ashoka, expanded the empire to its greatest extent. The brutal Kalinga War killed over 100,000 people.",
      },
      {
        placeholder_id: "section_4",
        text: "Horrified by the bloodshed, Ashoka embraced Buddhism and non-violence. His edicts, carved into rocks and pillars, promoted dharma, tolerance, and welfare.",
      },
      {
        placeholder_id: "section_5",
        text: "The Ashoka Chakra from his Lion Capital at Sarnath appears on India's national flag to this day — a lasting symbol of his legacy.",
      },
      {
        placeholder_id: "section_6",
        text: "After Ashoka's death, the empire weakened due to succession disputes and economic strain. The last Maurya king was assassinated in 185 BCE.",
      },
      { placeholder_id: "cta", text: "FOR MORE SUCH CONTENT : STAY CONNECTED WITH SUVICHAAR" },
    ],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-666666666666",
    mode: "news",
    template_key: "test-news-org",
    category: "Business",
    input_language: "en",
    slide_count: 5,
    image_source: "ai",
    voice_engine: "azure_basic",
    title: "Reliance and Disney+ Merge Streaming Operations in India",
    slug: "reliance-disney-merge-streaming-operations-india",
    timestamp_id: "150626104800912",
    description:
      "JioCinema and Disney+ Hotstar officially merge, creating India's largest OTT platform with 500M+ subscribers.",
    keywords: ["Reliance", "Disney+", "JioCinema", "OTT", "Streaming", "Business"],
    created_at: "2026-06-15T10:48:00Z",
    slides: [
      { placeholder_id: "cover", text: "Reliance and Disney+ Merge Streaming Operations in India" },
      {
        placeholder_id: "section_1",
        text: "In a landmark deal, Reliance Industries and The Walt Disney Company have officially merged their streaming platforms — JioCinema and Disney+ Hotstar — into a single entity.",
      },
      {
        placeholder_id: "section_2",
        text: "The combined platform will have over 500 million subscribers, making it the largest OTT service in Asia and a serious competitor to Netflix globally.",
      },
      {
        placeholder_id: "section_3",
        text: "The merged entity will house all IPL cricket, HBO originals, Marvel content, and Jio Studios productions under one roof at competitive pricing.",
      },
      { placeholder_id: "cta", text: "FOR MORE SUCH CONTENT : STAY CONNECTED WITH SUVICHAAR" },
    ],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-777777777777",
    mode: "news",
    template_key: "test-news-3v1",
    category: "World",
    input_language: "hi",
    slide_count: 4,
    image_source: "custom",
    voice_engine: "elevenlabs_pro",
    title: "चंद्रयान-4: ISRO ने चांद पर सैंपल रिटर्न मिशन की तारीख तय की",
    slug: "chandrayaan-4-isro-moon-sample-return-mission-date",
    timestamp_id: "150626113045678",
    description: "ISRO ने 2028 में चंद्रयान-4 लॉन्च की योजना बनाई — चांद से मिट्टी के नमूने लाने का भारत का पहला मिशन",
    keywords: ["ISRO", "Chandrayaan-4", "Moon", "Space", "India", "Science"],
    created_at: "2026-06-15T05:30:00Z",
    slides: [
      { placeholder_id: "cover", text: "चंद्रयान-4: ISRO ने चांद पर सैंपल रिटर्न मिशन की तारीख तय की" },
      {
        placeholder_id: "section_1",
        text: "ISRO ने घोषणा की कि चंद्रयान-4 मिशन 2028 में लॉन्च होगा। यह भारत का पहला चंद्र सैंपल रिटर्न मिशन होगा जो चांद की सतह से मिट्टी के नमूने लेकर पृथ्वी पर लाएगा।",
      },
      {
        placeholder_id: "section_2",
        text: "मिशन में तीन मॉड्यूल होंगे — ऑर्बिटर, लैंडर-एसेंडर, और रिटर्न कैप्सूल। ISRO के अध्यक्ष ने कहा कि यह मिशन भारत को चंद्र अन्वेषण में अगले स्तर पर ले जाएगा।",
      },
      { placeholder_id: "cta", text: "FOR MORE SUCH CONTENT : STAY CONNECTED WITH SUVICHAAR" },
    ],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-888888888888",
    mode: "curious",
    template_key: "curious-template-1",
    category: "Culture",
    input_language: "hi",
    slide_count: 7,
    image_source: "pexels",
    voice_engine: "azure_basic",
    title: "राजस्थान की रंगीन परंपराएं — Vibrant Traditions of Rajasthan",
    slug: "vibrant-traditions-of-rajasthani-culture",
    timestamp_id: "140626201530892",
    description:
      "Explore the rich and colorful heritage of Rajasthan — from folk art to festivals that have inspired generations.",
    keywords: ["Rajasthan", "Culture", "Heritage", "Festivals", "Folk Art", "India"],
    created_at: "2026-06-14T20:15:00Z",
    slides: [
      { placeholder_id: "cover", text: "राजस्थान की रंगीन परंपराएं — Vibrant Traditions of Rajasthan" },
      {
        placeholder_id: "section_1",
        text: "राजस्थान, भारत का सबसे बड़ा राज्य, इतिहास और भव्यता से भरा है। जयपुर और जोधपुर के विशाल किलों से लेकर उदयपुर की शांत झीलों तक, हर कोना वीरता और कला की कहानी कहता है।",
      },
      {
        placeholder_id: "section_2",
        text: "पुष्कर मेला, तीज, और डेज़र्ट फेस्टिवल जैसे त्योहार पूरे राज्य को संगीत, नृत्य और रंगीन पोशाकों से जीवंत कर देते हैं। घूमर नृत्य, जो महिलाएं लहराते घाघरों में करती हैं, एक अद्भुत दृश्य है।",
      },
      {
        placeholder_id: "section_3",
        text: "राजस्थानी कारीगर ब्लॉक प्रिंटिंग, ब्लू पॉटरी, और जटिल ज्वेलरी के लिए दुनिया भर में प्रसिद्ध हैं। ये शिल्प पीढ़ियों से चले आ रहे हैं।",
      },
      {
        placeholder_id: "section_4",
        text: "दाल बाटी चूरमा, लाल मांस, और कचौड़ी — राजस्थानी खाना अपने तीखे स्वाद और देसी घी के लिए जाना जाता है।",
      },
      {
        placeholder_id: "section_5",
        text: "राजस्थान सिर्फ एक राज्य नहीं, बल्कि एक जीवित विरासत है — जहाँ हर पत्थर, हर रंग, और हर गीत एक कहानी सुनाता है।",
      },
      { placeholder_id: "cta", text: "FOR MORE SUCH CONTENT : STAY CONNECTED WITH SUVICHAAR" },
    ],
  },
];
